version: 0.2

phases:
    install:
        commands:
            - echo Entered the install phase
            
    pre_build:
        commands:
            - echo Entered the pre_build phase..
    build:
        commands:
            - sudo su
            - yum install -y yum-utils
            - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            - yum install -y terraform
            - terraform init
            
            - terraform destroy --auto-approve
    post_build:
        commands:
            - echo Entered the post_build phase..
