version: 0.2

phases:
    install:
        commands:
            - echo Entered the install phase
            - apt-get update -y
    pre_build:
        commands:
            - echo Entered the pre_build phase..
    build:
        commands:
            - terraform apply --auto-approve
    post_build:
        commands:
            - echo Entered the post_build phase..
