version: 0.2

phases:
    install:
        commands:
            - echo Entered the install phase
            
    pre_build:
        commands:
            - echo Entered the pre_build phase..
    build:
        commands:
            - sudo yum install -y yum-utils
            - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            - sudo yum install -y terraform
            - terraform apply --auto-approve
    post_build:
        commands:
            - echo Entered the post_build phase..
